### ISSUE TITLE
[Question] Block helpers

### ISSUE THREAD

**Issue by sir-dunxalot** [tildeio/htmlbars#307]
In Handlebars one can utilize block helpers to create scopeless wrapping. This was incredibly useful for making HTML more maintainable without adding JS overhead. For example:

```hbs
{{!--app/templates/index.hbs--}}

{{#page-content}}
  {{!--References the index view--}}
  <p>Some property is {{view.someProperty}}</p>
{{/page-content}}
```

```js
// app/helpers/page-content.js

export default function(options) {
  var open = '<div class="content">';
  var close = '</div>';

  options.data.buffer.push('\n' + open);

  if (options.fn(this)) {
    options.data.buffer.push('\n' + options.fn(this));
  }

  options.data.buffer.push('\n' + close);

  return;
};
```

Is there a way to achieve similar functionality with HTMLBars? I know it's not a recommended use case but I'd like to know if it's possible.

Thank you in advance,
Duncan

**Comment by marcioj** [comment]
I believe that Martin or Matthew can give a better explanation, but based on my knowledge isn't a good idea to use `data.buffer` in your helper, in truth you not even can refer to `options.data.buffer` in your helpers in ember 1.10. And buffer is a `Ember.RenderBuffer` instance not a htmlbars thing. So since `data.buffer` isn't documented you may have some problems when upgrading. In this case, I would rather use a component like this http://emberjs.jsbin.com/wejupugora/1/edit?html,js,output

**Comment by sir-dunxalot** [comment]
Hi Marcio, thanks for the response! I know it's a pretty awful use of helpers but it is incredibly handy to not add unnecessary scope but keep the HTML maintainable.

The approach I've preferred since deprecating the block helper approach is two helpers (e.g. `{{page-content-open}}` and `{{page-content-close}}`), which return HTML blocks, or an open and close helper (e.g. `{{open 'page-content'}}`). Both do the job but I'd be nicer if it the syntax could match HTMLBars `#` and `/` more closely. Definitely trying to squeeze water out of a rock here haha...

**Comment by sir-dunxalot** [comment]
If anyone comes across this issue in the future: https://github.com/sir-dunxalot/ember-htmlbars-tags
